name: ringing_tutorial
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  firebase_core: ^4.1.1
  firebase_messaging: ^16.0.2
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.4
  stream_video: ^1.0.2
  stream_video_flutter: ^1.0.2
  stream_video_push_notification: ^1.0.2
  uuid: ^4.5.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
